### ISSUE TITLE
Chapter 8 Celery sock.connect(sa)\nConnectionRefusedError: [Errno 61]

### ISSUE THREAD

**Issue by alexstelmakh** [PacktPublishing/Django-4-by-example#34]
My code looks exactly as in the book. RabbitMQ is running, Celery as well but when I'm trying to complete my order Celery's CLI
throws a bunch of errors:
```
[2023-02-26 12:50:39,243: INFO/MainProcess] celery@mba.local ready.
[2023-02-26 12:52:13,824: INFO/MainProcess] Task orders.tasks.order_created[fff989e3-98e6-4ac3-adbc-9c791eea31d2] received
[2023-02-26 12:52:14,020: WARNING/ForkPoolWorker-8] --- Logging error ---
[2023-02-26 12:52:14,023: WARNING/ForkPoolWorker-8] Traceback (most recent call last):
[2023-02-26 12:52:14,024: WARNING/ForkPoolWorker-8]   File "/Users/el/Documents/Code/django_by_example/shop/env/shop/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
...
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 851, in create_connection\n    raise exceptions[0]\n  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 836, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [Errno 61] Connection refused\n', 'args': '[9]', 'kwargs': '{}', 'description': 'raised unexpected', 'internal': False}
```
My system is MacOS Ventura 13.2.1 maybe it is related somehow. Did someone faced such problem? Any help is really appreciated.

**Comment by alexstelmakh** [comment]
Problem solved by adding 'broker_url' parameter during the instantiation of Celery app. 
```
app = Celery('myshop', broker_url = 'amqp://guest:guest@localhost:5672/')
```
